name: Game Api CI/CD

on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: [opened, synchronize]

jobs:
    build:
        name: Build the solution
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build solution
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - run: |
            dotnet restore
            dotnet build --no-restore --configuration Release

    unit-tests:
        name: Run unit tests
        needs: [build]
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build solution
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - run: |
            dotnet restore
            dotnet build --no-restore --configuration Release

        - name: Execute unit tests
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - run: dotnet test --logger trx
       
        - name: Create Test Report
          uses: dorny/test-reporter@v2
          if: always()
          with:
            name: .NET Tests Report
            path: "**/*.trx"
            reporter: dotnet-trx
            fail-on-error: true



